controllers:
    resource: ../src/Controller/
    type: attribute

login:
    path: /login
    controller: App\Controller\SecurityController::login

registration:
    path: /register
    controller: App\Controller\RegistrationController::register

profile:
    path: /profile
    controller: App\Controller\ProjectController::index

settings:
    path: /settings
    controller: App\Controller\SettingsController::index

dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index
